networks:
  paymentapp-net:
    name: paymentapp-net
    driver: bridge

services:
  postgres:
    image: postgres:15
    container_name: paymentapp-postgres
    environment:
      POSTGRES_DB: PaymentAppDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Your_password123
    ports:
      - "15437:5432"
    volumes:
      - paymentapp_pgdata:/var/lib/postgresql/data

  api:
    container_name: paymentapp-api
    build:
      context: ..
      dockerfile: src/PaymentApp.Api/Dockerfile
    ports:
      - "5141:5141"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://*:5141"
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=PaymentAppDb;Username=postgres;Password=Your_password123"
    networks:
      - paymentapp-net

volumes:
  paymentapp_pgdata: